# Meta config
[global]
  checkNewVersion = true
  sendAnonymousUsage = true
[log]
  level="INFO"
[providers]
  [providers.docker]
    exposedByDefault="false"
    endpoint = "unix:///var/run/docker.sock"
[api]
  debug="true"
  ########################################################
# Proxy Config
[entryPoints]
  [entryPoints.web]
    address=":8090"
  [entryPoints.websecure]
    address = ":443"
  [entryPoints.dashboard]
#   ########################################################
#   # REFERENCE_FOR_CREATING_CERT
#   [http]
#     [http.middlewares]
#       [http.middlewares.redirect-to-https.redirectScheme]
#         scheme="https"
#     [http.routers]
#       [http.routers.redirs]
#         rule="hostregexp(`{host:.+}`)"
#         entryPoints=["web"]
#         middlewares=["redirect-to-https"]
#   ########################################################
# [certificatesResolvers]
#   [certificatesResolvers.fe-cert]
#     [certificatesResolvers.fe-cert.acme]
#       email="rumanbsl@gmail.com"
#       storage="/acme-cert.json"
#       caserver="https://acme-staging-v02.api.letsencrypt.org/directory"
#     [certificatesResolvers.fe-cert.acme.tlsChallenge]
#   ########################################################
